# Generated by Django 3.1.2 on 2020-10-25 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='название')),
                ('annons', models.CharField(max_length=250, verbose_name='аннонс')),
                ('full_text', models.TextField(verbose_name='статья')),
                ('date', models.DateTimeField(verbose_name='дата публикации')),
            ],
        ),
    ]
